formulaire:
    resource: "@FormulaireBundle/Controller/"
    type:     annotation
    prefix:   /

front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation
