admin_categorie:
    resource: "@AdminBundle/Controller/CategorieController.php"
    type:     annotation

front_formulaire_secours:
    resource: "@FrontBundle/Controller/FormulaireSecoursController.php"
    type:     annotation

actualite_actualite:
    resource: "@ActualiteBundle/Controller/ActualiteController.php"
    type:     annotation


admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /admin



front:
    resource: "@FrontBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: "@AppBundle/Controller/"
    type:     annotation


actualite:
    resource: "@ActualiteBundle/Controller/"
    type:     annotation
    prefix:   /admin

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

gallery:
    resource: '@SonataMediaBundle/Resources/config/routing/gallery.xml'
    prefix: /media/gallery

media:
    resource: '@SonataMediaBundle/Resources/config/routing/media.xml'
    prefix: /media

sonata_cache_cache:
    resource: '@SonataCacheBundle/Resources/config/routing/cache.xml'
    prefix: /

sonata_page_exceptions:
    resource: '@SonataPageBundle/Resources/config/routing/exceptions.xml'
    prefix: /

sonata_page_cache:
    resource: '@SonataPageBundle/Resources/config/routing/cache.xml'
    prefix: /